version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.0
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install tox
      PYTHONPATH="~/.local/bin" python3 -m tox


#prepare_tox: &prepare_tox,
#  run:
#    name: Install tox
#    command: |
#      sudo pip install --upgrade pip
#      pip install --user tox

jobs:
  test_app_api:
    <<: *defaults
    working_directory: ~/project/app/
    steps:
      - checkout:
          path: ~/project
      - *prepare_venv
      - run:
          name: Running app API test
          command: |
            tox

  publish_docker_image_to_aws:
    <<: *defaults
    working_directory: ~/project/
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publishing docker image to aws ECR
          command: |
            sudo pip install awscli
            eval $(aws ecr get-login --no-include-email --region us-east-1)
            make build-ml-api-aws tag-ml-api push-ml-api-aws
            aws ecs update-service --cluster ml-api-cluster --service custom-service --task-definition  first-run-task-definition --force-new-deployment


workflows:
  version: 2
  full_run:
    jobs:
      - test_app_api
      - publish_docker_image_to_aws:
          requires:
            - test_app_api
          filters:
            branches:
              only:
                - cicd_script

